### ISSUE TITLE
Porting to Plasma 6

### ISSUE THREAD

**Issue by nuqleo** [blackadderkate/weather-widget-2#157]
Hi,

Widget doesn't work in Plasma 6
```
This Widget was written for an unknown older version of Plasma 
and is not compatible with Plasma 6. Please contact the widget's 
author for an updated version.
```

**Comment by blackadderkate** [comment]
Oh no. I've been looking at this today and this breaks SO many things...  \<facepalm emoji\>

**Comment by als-creator** [comment]
So is the transition to qt6 planned or not? beta version of kde wayland is already running

**Comment by nuqleo** [comment]
Porting Plasmoids to KF6
https://develop.kde.org/docs/plasma/widget/porting_kf6/

**Comment by blackadderkate** [comment]
@nuqleo Yeah, I've seen that. Doesn't help.

Components and properties present in Qt5 seem to have just _vanished_ in Qt6 - which has **really** broken the Configuration pages...

onActionChosen, TableViewColumn, Spinbox.suffix, styleData.row - all just vanished without a trace, and no documentation on what to replace them with..

I **am** making progress - the basic widget and meteogram work (but need polishing), and the General Config page sorta works (but not adding new locations).

**Comment by blackadderkate** [comment]
I have pushed my work-to-date onto a new QT6 branch. This DOESN'T WORK yet...


At the moment MetNo is hardcoded to download from an internal web-server while I'm testing.
You can TRY hacking the MetNo.qml file to download live data but it probably won't work as an old issue has reappeared - data doesn't get downloaded unless you provide User-agent headers.
(see https://github.com/blackadderkate/weather-widget-2/issues/89#issuecomment-1075689558). I have added code to supply User-agent headers, but this hasn't been tested yet - once the widget works the way it's supposed to THEN I'll worry about retrieving the data from the MetNo server. ;-)

And the config pages are broken/unfinished...

Oh yes, and you can't install it into the system tray yet - only into a panel / onto the desktop...

But apart from that it's working! :-D

**Comment by nuqleo** [comment]
Unpacked package directory from QT6 branch in ~/.local/share/plasma/plasmoids/org.kde.weatherWidget-2.
Still getting error "This Widget was written for an unknown older version of Plasma".

**Comment by blackadderkate** [comment]
Should work now (it works on my development VM anyway).
I accidentally included a folder that I shouldn't have.

**Comment by blackadderkate** [comment]
> Should work now (it works on my development VM anyway). I accidentally included a folder that I shouldn't have.

Sigh. It works using plasmoidviewer, but not if you install the plasmoid. 

Apparently the json file is invalid - even though I used **their** own conversion tool to create it...

`KPackageStructure of KPluginMetaData(pluginId:"org.kde.weatherWidget-2", fileName: "org.kde.weatherWidget-2/metadata.json") does not match requested format "Plasma/Applet".`

The **Porting guide for Plasmoids to KF6/Plasma6** page SEVERELY misrepresents how easy it is in practice...

**Comment by blackadderkate** [comment]
I fixed the json file.

It works with plasmawindowed AND plasmoidviewer, but the Add Widget tool still says it's invalid. I'm baffled...

**Comment by blackadderkate** [comment]
I applied the patch and it works now!
I submitted a bug report to KDE, and they have now updated their instructions...

**Comment by blackadderkate** [comment]
OK, I've just published an alpha version for testing ([see here](https://github.com/blackadderkate/weather-widget-2/releases/tag/v3.0a1)). There are a few issues with this release - please read the release notes before filing any bug reports!

Speaking of which, as it's only an alpha version I don't really want to clutter up the issues system with minor gripes - only show-stopping bugs at this stage.
Please report any trivial issues and gripes - or any suggestions on how to fix any of the issues mentioned in the Release Notes - [on this discussion thread](https://github.com/blackadderkate/weather-widget-2/discussions/161) instead.

**Comment by nuqleo** [comment]
Thanks.

Only OWM works for me.

**Comment by blackadderkate** [comment]
Hmm, MetNo works for me on openSuse Krypton on my virtual machine - what distribution are you running?

Let's see if we can track down where it's failing...

Change the **debugLogging** setting in` .local/share/plasma/plasmoids/org.kde.weather-widget-3/content/config/main.xml` to **true**.

open **konsole**, and type `plasmashell --replace`

That should restart plasma and reload the widget, which  _should_ dump out loads of debugging information to the Konsole - you may be able to spot an obvious error in there. If not, an you please copy the whole lot into a textfile and upload it here for me to analyse...

I have a sneaking suspicion it _might_ be something to do with the http headers - possibly User Agent...

**Comment by als-creator** [comment]
>Only OWM works for me.

I also probably have something to do with sanctions against Russia.

**Comment by solbu** [comment]
> > Only OWM works for me.
> 
> I also probably have something to do with sanctions against Russia.

Nope.
The Norwegian Meteorological Institute does not block anyone due to sanctions.

**Comment by als-creator** [comment]
Well, it worked for me in Russia, and then it stopped showing in 2023, I decided that it was because of sanctions, now I use owm

**Comment by PureTryOut** [comment]
Switching between OWM and MetNo changes the UI quite a lot, the only reason I use OWM is because I find it looks way better than MetNo. I don't understand why the UI is completely different, but could that also be changed with the porting to Plasma 6?

**Comment by blackadderkate** [comment]
> Switching between OWM and MetNo changes the UI quite a lot, the only reason I use OWM is because I find it looks way better than MetNo. I don't understand why the UI is completely different, but could that also be changed with the porting to Plasma 6?

The answer is that the free version of the OWM API provides less data than MetNo. Their Short-Range Data is 3-hourly instead of hourly, and Long-Range Data is for 5 days rather than 8 days.

This makes the Meteogram graph smoother (but less accurate), and reduces how far into the future the app can predict.

Living in the UK - where the weather is incredibly unpredictable and you can get all four seasons in one day - the extra information provided by the MetNo interface is worth the clutter IMHO...

**Comment by nuqleo** [comment]
```
file:///home/user/.local/share/plasma/plasmoids/org.kde.weatherWidget-3/contents/ui/providers/MetNo.qml:97: TypeError: Cannot read property 'data' of undefined
```

**Comment by blackadderkate** [comment]
> ```
> file:///home/user/.local/share/plasma/plasmoids/org.kde.weatherWidget-3/contents/ui/providers/MetNo.qml:97: TypeError: Cannot read property 'data' of undefined
> ```
I think that's a timezone-related issue...
I've just uploaded a patch & new version of the plasmoid that _hopefully_ should fix it...

**Comment by nuqleo** [comment]
MetNo works now but the forecast is shown only for 3 days for MetNo and for 5 days for OWM.

**Comment by blackadderkate** [comment]
> MetNo works now but the forecast is shown only for 3 days for MetNo and for 5 days for OWM.

I committed a LOT of patches yesterday, and even more today - [please try the latest build (v3.0a5)](https://github.com/blackadderkate/weather-widget-2/releases/tag/v3.0a5) that I've just uploaded.
It seems to work pretty well on my VirtualBox test machine on various timezones...

**Comment by nuqleo** [comment]
MetNo forecast is shown now for 9 days but for OWM only for 5 days.
Also cloud icon on panel became huge.

**Comment by blackadderkate** [comment]
![Screenshot_20240129_221936](https://github.com/blackadderkate/weather-widget-2/assets/83865293/319f23b6-a964-4bd2-bf84-f3cd5f76150b)
> MetNo forecast is shown now for 9 days but for OWM only for 5 days. Also cloud icon on panel became huge.

You can change the cloud icon size by changing the font size in the settings (under Appearance) - that's still a work-in-progress.

OWM is only showing 5 days forecast on the Plasma 5 version of the widget on my laptop too (see screenshot)  - so that's not a bug with the Plasma 6 widget as such.

Looking at the OWM website, they appear to have changed the amount of forecast data they offer in their free package - I don't think I can do much about that, to be honest but I will check...

**Comment by nuqleo** [comment]
OWM shows 8 days on the Plasma 5 version widget and on site.

**Comment by blackadderkate** [comment]
> OWM shows 8 days on the Plasma 5 version widget and on site.

I hadn't had to work much on the OWM code before, as their API hasn't changed since the original widget was created.

Having investigated the code, it looks as though there's an undocumented (or obsolete) API containing the missing data. 

I've started writing code, but due to the changes in Plasma 6 / QML 6, this is not going to be a quick fix...

**Comment by blackadderkate** [comment]
[New version of the widget released...](https://github.com/blackadderkate/weather-widget-2/releases/download/v3.0a6/weather-widget-3.0a6.plasmoid)

I have reduced the font size and added the missing (undocumented) OWM data. Since this is undocumented, it may well be obsolete and could disappear without notice at any time...
Some Timezone related fixes (I hope).

**Comment by nuqleo** [comment]
All days are shown now both for OWM and met.no.
After desktop start bottom link to owm or met.no site is not shown. Need to switch to other place to show it.

**Comment by blackadderkate** [comment]
> After desktop start bottom link to owm or met.no site is not shown. Need to switch to other place to show it.

I can't reproduce this on my test box, but I have changed the order things are processed to be on the safe side.  I will upload a new version sometime next week.

**Comment by als-creator** [comment]
![image](https://github.com/blackadderkate/weather-widget-2/assets/25702710/67e3ec26-4f4b-4554-82b7-d4015b41acbb)
If a new version for Plasma 6 is released, can you add it to the KDE store in the plasma 6 section so that it can be installed?

**Comment by blackadderkate** [comment]
> ![image](https://private-user-images.githubusercontent.com/25702710/308646612-67e3ec26-4f4b-4554-82b7-d4015b41acbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMzQyMDcsIm5iZiI6MTcwOTIzMzkwNywicGF0aCI6Ii8yNTcwMjcxMC8zMDg2NDY2MTItNjdlM2VjMjYtNGY0Yi00NTU0LTgyYjctZDQwMTViNDFhY2JiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDE5MTE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliYTc2NDA4ZDUyNTE2ZjBkNzFjMTRkNmU5NmEzMjVkODYxZDFiN2E3YjVjMTJjOWZiMTM2OTA0NjljMDkwNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UxQTtgMbzRVKJhRDaFX5CRXjboRdQhXwCH9BtNJ8iYA) If a new version for Plasma 6 is released, can you add it to the KDE store in the plasma 6 section so that it can be installed?

Yes, when I have it working properly - right now it still has some bugs in it, and if I release it now I will just be bombarded with bug reports that I know about and am already working on.

If you _really_  need it - **bearing in mind there are still some bugs in it** - [please follow the instructions here](https://github.com/blackadderkate/weather-widget-2/discussions/161#discussioncomment-8634762) on how to download it and install it manually...

**Comment by als-creator** [comment]
can I add a font color setting? I've tried different desktop themes in the alpha version, the font color is black everywhere

![image](https://github.com/blackadderkate/weather-widget-2/assets/25702710/9b06b8a1-d52a-4d41-b5f0-a0ba3157858f)

![image](https://github.com/blackadderkate/weather-widget-2/assets/25702710/2da60fa2-d05f-4ea0-82a4-4ce86ebdd3ae)

**Comment by blackadderkate** [comment]
It is supposed to use the theme font colour, but I think I know the cause...

**Comment by blackadderkate** [comment]
OK, fixed that.
Also fixed the colours in the tableView on the Configuration Page, and the MetNo Search tableView.
Also fixed the weird issue where scrolling horizontally would change the Row Height on the MetNo Search tableView.

[New version here.](https://github.com/blackadderkate/weather-widget-2/releases/tag/v3.0b1a)

**Comment by als-creator** [comment]
> OK, fixed that. Also fixed the colours in the tableView on the Configuration Page, and the MetNo Search tableView. Also fixed the weird issue where scrolling horizontally would change the Row Height on the MetNo Search tableView.
> 
> [New version here.](https://github.com/blackadderkate/weather-widget-2/releases/tag/v3.0b1a)

its not working for this version, all theme not working, font not light

![image](https://github.com/blackadderkate/weather-widget-2/assets/25702710/5ed11864-520d-48d8-aa95-6a5668aea163)

![image](https://github.com/blackadderkate/weather-widget-2/assets/25702710/8088d288-6e2d-4ed2-b310-2f2372bd115b)

![image](https://github.com/blackadderkate/weather-widget-2/assets/25702710/4ae2ea58-486b-4540-814d-22579ac341dd)
![image](https://github.com/blackadderkate/weather-widget-2/assets/25702710/a3a0cdee-0f7c-4b34-9df3-0cd31c854fd9)

**Comment by blackadderkate** [comment]
> > OK, fixed that. Also fixed the colours in the tableView on the Configuration Page, and the MetNo Search tableView. Also fixed the weird issue where scrolling horizontally would change the Row Height on the MetNo Search tableView.
> > [New version here.](https://github.com/blackadderkate/weather-widget-2/releases/tag/v3.0b1a)
> 
> its not working for this version, all theme not working, font not light
> 

Works on my development Virtual Machine using Breeze Dark theme (see below).
![Screenshot_20240305_124043](https://github.com/blackadderkate/weather-widget-2/assets/83865293/8ca92bf8-3084-4827-a6ba-ae406f6eb351)

Either I messed up building the plasmoid, or the plasmoid didn't update/install correctly...

I suggest you delete the ~/.local/share/plasma/plasmoids/org.kde.weatherWidget-3/ folder, download and install [this version](https://github.com/blackadderkate/weather-widget-2/releases/download/v3.0b1b/weather-widget-3.0.0b1.plasmoid) (which is slightly newer), and reboot, logoff/login again, or restart plasmashell with plasmashell --replace.

**Comment by als-creator** [comment]
everything is fine now, probably needed a reboot
![image](https://github.com/blackadderkate/weather-widget-2/assets/25702710/cb311146-070d-4e6e-9973-982be9de4827)

**Comment by als-creator** [comment]
In this beta version the weather forecast from metno does not work, own works fine

![image](https://github.com/blackadderkate/weather-widget-2/assets/25702710/e2c7cd41-b2a4-4382-8047-f5277bbfdc21)

![image](https://github.com/blackadderkate/weather-widget-2/assets/25702710/637dae9e-8064-4b64-8433-c881654d9f7e)

**Comment by Drommer** [comment]
I used the packages 'qt5-graphicaleffects' and 'qt5-xmlpatterns' as dependencies for KDE Plasma 5 (Arch Linux). Should I remove/replace it for Plasma 6?

**Comment by als-creator** [comment]
> I used the packages 'qt5-graphicaleffects' and 'qt5-xmlpatterns' as dependencies for KDE Plasma 5 (Arch Linux). Should I remove/replace it for Plasma 6?


xmlpatterns was responsible for display, for the new version of the widget it most likely is not needed, in any case, you can use Pacman keys and clear the orphan packages and look at the dependencies
https://wiki.archlinux.org/title/pacman

I only have a keyboard trainer that requires it like an addiction

![image](https://github.com/blackadderkate/weather-widget-2/assets/25702710/229d5244-c3d5-4f69-8c12-678c2bb6828f)

qt5-graphicaleffects needed for many programs

![image](https://github.com/blackadderkate/weather-widget-2/assets/25702710/9ed09a62-cde7-46c8-aa23-ca3a860cc7c4)

**Comment by blackadderkate** [comment]
> In this beta version the weather forecast from metno does not work, own works fine
> 
> ![image](https://private-user-images.githubusercontent.com/25702710/310561646-e2c7cd41-b2a4-4382-8047-f5277bbfdc21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MzU1ODMsIm5iZiI6MTcwOTgzNTI4MywicGF0aCI6Ii8yNTcwMjcxMC8zMTA1NjE2NDYtZTJjN2NkNDEtYjJhNC00MzgyLTgwNDctZjUyNzdiYmZkYzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDE4MTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZGQ0MWI1OGJmMmYxNjI0NWEyZWVmZGEwM2I2MWI0OTIwNWY3YmYwM2I4MGJlYzA4ZjQ3M2M5MDZhM2RiYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FGvBfqZivko39TRudnxhaEtaQbwQOKwvpSOGjrWDVrs)
> 
> ![image](https://private-user-images.githubusercontent.com/25702710/310562080-637dae9e-8064-4b64-8433-c881654d9f7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MzU1ODMsIm5iZiI6MTcwOTgzNTI4MywicGF0aCI6Ii8yNTcwMjcxMC8zMTA1NjIwODAtNjM3ZGFlOWUtODA2NC00YjY0LTg0MzMtYzg4MTY1NGQ5ZjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDE4MTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmNTQ0NjY1Y2E2YzcyNjU1MWE2OTE1M2VmYzU1MzUzMDcxNjc1NWI5ZmZmY2YwNmQwZGIzMTcwNzRiYThiMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1DvshPVKH3s78iu80JhMMIj0R1XeblsH25wAHV-3OzI)

I can't reproduce this on my Development box. Does it work if you use the default MetNo locations bundled with the plasmoid?

Could you try the following for me:

in Konsole:

cd ~/.local/share/plasa/plasmoids/org.kde.weatherWidget-3
plasmoidviewer -a .

And post a copy of the output or error messages? That shoul help me narrow down the problem...

**Comment by blackadderkate** [comment]
> I used the packages 'qt5-graphicaleffects' and 'qt5-xmlpatterns' as dependencies for KDE Plasma 5 (Arch Linux). Should I remove/replace it for Plasma 6?

I'm running OpenSuse Tumbleweed rather than ArchLinux on my development/testing VM, but I _think_ these are the ArchLinux dependencies required:

qt5-graphicaleffects ==> is now ==> qt6-5compat
qt5-xmlpatterns ==> is now ==> qt6-declarative

Please note: If I remember correctly, the widget needs compiling on ArchLinux? The Makefiles are currently broken, and I've no idea how to fix them. Filed as issue #163.

**Comment by als-creator** [comment]
> > In this beta version the weather forecast from metno does not work, own works fine
> > ![image](https://private-user-images.githubusercontent.com/25702710/310561646-e2c7cd41-b2a4-4382-8047-f5277bbfdc21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MzU1ODMsIm5iZiI6MTcwOTgzNTI4MywicGF0aCI6Ii8yNTcwMjcxMC8zMTA1NjE2NDYtZTJjN2NkNDEtYjJhNC00MzgyLTgwNDctZjUyNzdiYmZkYzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDE4MTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZGQ0MWI1OGJmMmYxNjI0NWEyZWVmZGEwM2I2MWI0OTIwNWY3YmYwM2I4MGJlYzA4ZjQ3M2M5MDZhM2RiYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FGvBfqZivko39TRudnxhaEtaQbwQOKwvpSOGjrWDVrs)
> > ![image](https://private-user-images.githubusercontent.com/25702710/310562080-637dae9e-8064-4b64-8433-c881654d9f7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MzU1ODMsIm5iZiI6MTcwOTgzNTI4MywicGF0aCI6Ii8yNTcwMjcxMC8zMTA1NjIwODAtNjM3ZGFlOWUtODA2NC00YjY0LTg0MzMtYzg4MTY1NGQ5ZjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDE4MTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmNTQ0NjY1Y2E2YzcyNjU1MWE2OTE1M2VmYzU1MzUzMDcxNjc1NWI5ZmZmY2YwNmQwZGIzMTcwNzRiYThiMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1DvshPVKH3s78iu80JhMMIj0R1XeblsH25wAHV-3OzI)
> 
> I can't reproduce this on my Development box. Does it work if you use the default MetNo locations bundled with the plasmoid?
> 
> Could you try the following for me:
> 
> in Konsole:
> 
> cd ~/.local/share/plasa/plasmoids/org.kde.weatherWidget-3 plasmoidviewer -a .
> 
> And post a copy of the output or error messages? That shoul help me narrow down the problem...

plasmoidviewer not found
plasmoidviewer-debug outdated

![image](https://github.com/blackadderkate/weather-widget-2/assets/25702710/a270df1d-01b9-4af7-98a9-50f3384731fc)
![image](https://github.com/blackadderkate/weather-widget-2/assets/25702710/be3a6164-d7e7-476a-87b2-8c1caafe7ab9)

**Comment by Drommer** [comment]
> qt5-graphicaleffects ==> is now ==> qt6-5compat
qt5-xmlpatterns ==> is now ==> qt6-declarative

Arch Linux has these packages too, the names are identical. Thank you.

> If I remember correctly, the widget needs compiling on ArchLinux? The Makefiles are currently broken, and I've no idea how to fix them.

Thank you for mentioning that. I switched to the 'QT6' branch and the compilation was successful. However, I encountered another problem. 
In my current user account (where the applet was added to the panel and configured) everything works fine after upgrading from Plasma 5 to Plasma 6 and upgrading the applet.
I created a new user to set up Plasma 6 cleanly, but adding an applet to the panel is not working. I see a message about incompatibility with the current version of Plasma. Any idea why this is happening?

**Comment by blackadderkate** [comment]
> > qt5-graphicaleffects ==> is now ==> qt6-5compat
> > qt5-xmlpatterns ==> is now ==> qt6-declarative
> 
> Arch Linux has these packages too, the names are identical. Thank you.
> 
> > If I remember correctly, the widget needs compiling on ArchLinux? The Makefiles are currently broken, and I've no idea how to fix them.
> 
> Thank you for mentioning that. I switched to the 'QT6' branch and the compilation was successful. However, I encountered another problem. In my current user account (where the applet was added to the panel and configured) everything works fine after upgrading from Plasma 5 to Plasma 6 and upgrading the applet. I created a new user to set up Plasma 6 cleanly, but adding an applet to the panel is not working. I see a message about incompatibility with the current version of Plasma. Any idea why this is happening?

The Plasma6 version is now called Weather-Widget-3. Make sure you're adding the correct version of the widget for that user - and double-check that the new user is using Plasma6 and not Plasma5 (just because it is installed doesn't mean the new user is using it by default).

**Comment by blackadderkate** [comment]
> > > In this beta version the weather forecast from metno does not work, own works fine
> > > ![image](https://private-user-images.githubusercontent.com/25702710/310561646-e2c7cd41-b2a4-4382-8047-f5277bbfdc21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MzU1ODMsIm5iZiI6MTcwOTgzNTI4MywicGF0aCI6Ii8yNTcwMjcxMC8zMTA1NjE2NDYtZTJjN2NkNDEtYjJhNC00MzgyLTgwNDctZjUyNzdiYmZkYzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDE4MTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZGQ0MWI1OGJmMmYxNjI0NWEyZWVmZGEwM2I2MWI0OTIwNWY3YmYwM2I4MGJlYzA4ZjQ3M2M5MDZhM2RiYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FGvBfqZivko39TRudnxhaEtaQbwQOKwvpSOGjrWDVrs)
> > > ![image](https://private-user-images.githubusercontent.com/25702710/310562080-637dae9e-8064-4b64-8433-c881654d9f7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MzU1ODMsIm5iZiI6MTcwOTgzNTI4MywicGF0aCI6Ii8yNTcwMjcxMC8zMTA1NjIwODAtNjM3ZGFlOWUtODA2NC00YjY0LTg0MzMtYzg4MTY1NGQ5ZjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDE4MTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmNTQ0NjY1Y2E2YzcyNjU1MWE2OTE1M2VmYzU1MzUzMDcxNjc1NWI5ZmZmY2YwNmQwZGIzMTcwNzRiYThiMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1DvshPVKH3s78iu80JhMMIj0R1XeblsH25wAHV-3OzI)
> > 
> > 
> > I can't reproduce this on my Development box. Does it work if you use the default MetNo locations bundled with the plasmoid?
> > Could you try the following for me:
> > in Konsole:
> > cd ~/.local/share/plasa/plasmoids/org.kde.weatherWidget-3 plasmoidviewer -a .
> > And post a copy of the output or error messages? That shoul help me narrow down the problem...
> 
> plasmoidviewer not found plasmoidviewer-debug outdated
> 
> ![image](https://private-user-images.githubusercontent.com/25702710/311010740-a270df1d-01b9-4af7-98a9-50f3384731fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NDQyNDcsIm5iZiI6MTcwOTg0Mzk0NywicGF0aCI6Ii8yNTcwMjcxMC8zMTEwMTA3NDAtYTI3MGRmMWQtMDFiOS00YWY3LTk4YTktNTBmMzM4NDczMWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDIwMzkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiOTU1ODJmN2UxNjY4MTY4NjYxOTBlMGQzOTM5ZDlmMzk5MmQ4ODBlNmFmMTE3MGZkZGU2OGFhY2I0M2EwMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5WTDcZqjFxCU0LrKB5Nm6xnlhjmC-d6cyhb79f1ZKCQ) ![image](https://private-user-images.githubusercontent.com/25702710/311010836-be3a6164-d7e7-476a-87b2-8c1caafe7ab9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NDQyNDcsIm5iZiI6MTcwOTg0Mzk0NywicGF0aCI6Ii8yNTcwMjcxMC8zMTEwMTA4MzYtYmUzYTYxNjQtZDdlNy00NzZhLTg3YjItOGMxY2FhZmU3YWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDIwMzkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZWYzMThiNGJkNDU5NmFlZjMwNzczYzZiYzM0N2NmOTk1OGUzYmFlZjdhOWE0NzYzMTdiOTA1NTU2MDJlYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IL0C1xlIjK8uZETXfoWtQ5yNQov5Kxi2oQ_5U07-6lU)

That doesn't help I'm afraid. :(
I shall have to install Arch on another VM to see if I can figure out what is going on - but it might take a few days...

**Comment by Drommer** [comment]
> The Plasma6 version is now called Weather-Widget-3. Make sure you're adding the correct version of the widget for that user - and double-check that the new user is using Plasma6 and not Plasma5 (just because it is installed doesn't mean the new user is using it by default).

Arch Linux replaced the Plasma 5 packages with Plasma 6, so I don't think this option is possible. In 'Settings => About System' it says that KDE Plasma 6.0.1, KDE Frameworks 6.0.0 and QT 6.6.2 are used. In the settings of the widget itself it specifies 'Weather Widget 3 3.0.0b1'

**Comment by blackadderkate** [comment]
OK, this is getting confusing - there are two different people with two different bugs.
I've added two issues #164 and #165 accordingly. Please can you post on those appropriate issues instead?

**Comment by als-creator** [comment]
> That doesn't help I'm afraid. :(
> I shall have to install Arch on another VM to see if I can figure out what is going on - but it might take a few days...


ready-made virtual machines for tests with logins and passwords can be downloaded [here](https://www.osboxes.org/)

**Comment by Drommer** [comment]
~~Compilation is broken again after the changes to the QT6 branch accepted two hours ago.~~

**Comment by galibozek** [comment]
For archlinux please try: https://aur.archlinux.org/packages/plasma-applets-weather-widget-2

**Comment by Drommer** [comment]
> Compilation is broken again after the changes to the QT6 branch accepted two hours ago.

@blackadderkate Adding the -DQT_MAJOR_VERSION=6 option to the build configuration fixed the error and the compilation was successful. But the resulting package is unusable because only the language package is packed into it (directly into the root instead of /usr/...). @RedSQL mentioned this in his merge request and the problem has not been fixed. I think request [#167](url=https://github.com/blackadderkate/weather-widget-2/pull/167) should be excluded until the bugs are fixed.

> For archlinux please try: https://aur.archlinux.org/packages/plasma-applets-weather-widget-2

@galibozek It doesn't work for the same reason.

![20240310_212612](https://github.com/blackadderkate/weather-widget-2/assets/36813829/f7fa93ec-d946-42d8-b819-f1d21ad36578)

**Comment by blackadderkate** [comment]
> > Compilation is broken again after the changes to the QT6 branch accepted two hours ago.
> 
> @blackadderkate Adding the -DQT_MAJOR_VERSION=6 option to the build configuration fixed the error and the compilation was successful. But the resulting package is unusable because only the language package is packed into it (directly into the root instead of /usr/...). @RedSQL mentioned this in his merge request and the problem has not been fixed. I think request #167 should be excluded until the bugs are fixed.
> 
> > For archlinux please try: https://aur.archlinux.org/packages/plasma-applets-weather-widget-2
> 
> @galibozek It doesn't work for the same reason.
> 
> ![20240310_212612](https://private-user-images.githubusercontent.com/36813829/311538868-f7fa93ec-d946-42d8-b819-f1d21ad36578.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMDE0NDcsIm5iZiI6MTcxMDEwMTE0NywicGF0aCI6Ii8zNjgxMzgyOS8zMTE1Mzg4NjgtZjdmYTkzZWMtZDk0Ni00MmQ4LWI4MTktZjFkMjFhZDM2NTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDIwMDU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlZTc1ZThjYmQ4ZGE0NDhjMDJlNDIxOWIyMTIwNzc5ZTk3MzgyNWIzOTA1Mjg1M2QwYmI4YmJlZTdkNTIzMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3YPbsFUPTGwcgCRhat6TQhdU0TU7M6DcbOdiBW6XtZQ)

Are you using the dev-install.sh script to compile? That sets the appropriate make options for installing the paths...

**Comment by galibozek** [comment]
@Drommer I fixed the directory structure, thanks. 
But it seems that there should be "weatherWidget-3" in "CMakeLists.txt" instead of "weatherWidget-2" in the paths? 
```
translations/po/CMakeLists.txt
translations/CMakeLists.txt
plugin/CMakeLists.txt
```
@blackadderkate

**Comment by Drommer** [comment]
> Are you using the dev-install.sh script to compile? That sets the appropriate make options for installing the paths...

@blackadderkate I used the build script for Arch Linux packages (PKGBUILD). The parameters for CMAKE in my PKGBUILD are identical to dev-build.sh.

```
build() {
  cd build
  cmake ../$_gitname \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DKDE_INSTALL_USE_QT_SYS_PATHS=ON \
        -DQT_MAJOR_VERSION=6
}

package() {
  cd build
  make DESTDIR="$pkgdir" install
}
```

**Comment by RedSQL** [comment]
> The resulting package is unusable because only the language package is packed into it (directly into the root instead of /usr/...). @RedSQL mentioned this in his merge request and the problem has not been fixed. I think request https://github.com/blackadderkate/weather-widget-2/pull/167 should be excluded until the bugs are fixed.

@Drommer Oh, that's weird. I haven't noticed that particular issue when using the `dev-build.sh` script! I didn't really mess with any paths and cmake args apart from `-DQT_MAJOR_VERSION=6` and the widget compiled fine so I assumed everything was good to go like it was back in Plasma 5. After investigating I indeed noticed that it was installing localization files in the root directory instead of `/usr`, and I missed a few compilation messages at the very top that have shown locales being installed in the root directory!
![image](https://github.com/blackadderkate/weather-widget-2/assets/22281670/a2dc6540-d4b4-4812-99a4-0dd05a1e0a86)
Woops! 😬

Looks like @galibozek have already got on the issue and got it fixed within the PKGBUILD over at AUR:
[Fix 1](https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=plasma-applets-weather-widget-2&id=4ebd4fe5deb4d719abc171abc3195f6677774507)
[Fix 2](https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=plasma-applets-weather-widget-2&id=35aad84adc923a2c445bda8af4a13657ae8bc80f)
[Fix 3](https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=plasma-applets-weather-widget-2&id=b29c4e5daf10888c5d411bb547f7d1a4f214beea)

**Comment by Drommer** [comment]
@RedSQL I've seen @galibozek's suggested option but it looks like a crutch for me. @lainedfles said in our discussion #165  that you need to make some significant changes to the source code of the widget in order to build properly with increased KF_MIN_VERSION and QT_MIN_VERSION values. His proposed variant was built without specifying explicit paths for files, which seems more reasonable and correct.

P.S. I'm not sure but maybe the problem is that in `CMakeLists.txt` in the 'plugin' and 'translations' directories the plugin name is wrong (-2 instead of -3)? Other files (cpp) have the same problem.

**Comment by galibozek** [comment]
> P.S. I'm not sure but maybe the problem is that in `CMakeLists.txt` in the 'plugin' and 'translations' directories the plugin name is wrong (-2 instead of -3)? Other files (cpp) have the same problem.

as I mentioned above, this is also a problem.

**Comment by RedSQL** [comment]
@Drommer I've just read the 165 and if I understand the discussion happening there, yeah that's true, relying on 'compatibility' libraries (e.g qt6-5compat or Plasma5Support) after toolkit changes their API majorly is a bit of a hacky solution. Compatibility libraries won't last around forever. 

Changes I've submitted were mostly made out of "get *something* working right now" thinking. Because widget works pretty okay in the current state and can compile, even if it pulls in `qt6-5compat`. I'd rather just put out a some form of solution, even if it is temporary. If that at any point changes the `Plasma5Support` and `qt6-5compat` can be dropped from the package as needed.

**Comment by blackadderkate** [comment]
> @RedSQL I've seen @galibozek's suggested option but it looks like a crutch for me. @lainedfles said in our discussion #165 that you need to make some significant changes to the source code of the widget in order to build properly with increased KF_MIN_VERSION and QT_MIN_VERSION values. His proposed variant was built without specifying explicit paths for files, which seems more reasonable and correct.
> 

As I understand it, Qt5Compat is a Qt6 library that provides Qt5 functionality missing in Qt6? Therefore that does not prevent increasing the KF_MIN_VERSION and QT_MIN_VERSION values? But I could be wrong...

> P.S. I'm not sure but maybe the problem is that in `CMakeLists.txt` in the 'plugin' and 'translations' directories the plugin name is wrong (-2 instead of -3)?

That sounds plausible.


**FYI I'm working significant overtime next week, so development and response times to comments/bug reports/pull requests might be slower than usual...**

**Comment by blackadderkate** [comment]
OK, I think I have quashed the last of major bugs.
See the releases page for [the first official release](https://github.com/blackadderkate/weather-widget-2/releases/tag/V3.0.0)!

Please report any bugs in the appropriate [discussion](https://github.com/blackadderkate/weather-widget-2/discussions/174), or [check if it has been raised as an issue](https://github.com/blackadderkate/weather-widget-2/issues).

**Comment by nuqleo** [comment]
On panel temperature overlapped by clouds. Was fine in b1.
