### ISSUE TITLE
Changing Units in the Configuration Page doesn't work

### ISSUE THREAD

**Issue by blackadderkate** [blackadderkate/weather-widget-2#73]
Changing Unit from (for example changing °C to °F ) doesn't work any more.

**Comment by blackadderkate** [comment]
This is due to the firstrun code - for some reason setting the variable as well as the plasmoid.configuration.property breaks things.

Fixed in commits b73b044 (master), 542d99a (legacy-version-for-older-qt-releases)

**Comment by pickfire** [comment]
Will there be a release for this anytime or had to wait, I also had this issue, the old weather widget don't have this isuse.

**Comment by traverseda** [comment]
Me too actually, just looked this up. Is there a work around?

**Comment by blackadderkate** [comment]
> Me too actually, just looked this up. Is there a work around?

> Will there be a release for this anytime or had to wait, I also had this issue, the old weather widget don't have this issue.

I have just [uploaded an updated version (2.2.4) onto Github](https://github.com/blackadderkate/weather-widget-2/releases/download/v2.2.4/weather-widget-2.2.4.plasmoid). A new version of the "legacy" version for older distributions will be uploaded shortly.

I will publish the update on the KDE store/Discover for full distribution in a couple of days - I need more time to test my changes more thoroughly before unleashing it on the general public.

If you need them, instructions on how to install / upgrade the widget manually [are available in the Wiki](https://github.com/blackadderkate/weather-widget-2/wiki/How-to-install-the-Widget---manual-download).

**Comment by blackadderkate** [comment]
OK, the version I released had some nasty bugs in certain Locales (see issues #78 and #79).

If you live in a country that uses Commas instead of Period Marks for decimals (such as Germany), you should probably [download release 2.2.4.2](https://github.com/blackadderkate/weather-widget-2/releases/download/v2.2.4/weather-widget-2.2.4.2.plasmoid)

**Comment by mikewii** [comment]
This bug still present with 2.3.4 and in 2.2.4.2 it just change symbol, not the actual numbers
Tested on Debian 11, 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2, KDE Plasma Version 5.20.5

**Comment by mikewii** [comment]
nvm, in 2.2.4.2 it do nothing as well, and there is no units section in config file at .config/plasma-org.kde.plasma.desktop-appletsrc for org.kde.weatherWidget-2

**Comment by blackadderkate** [comment]
> This bug still present with 2.3.4 and in 2.2.4.2 it just change symbol, not the actual numbers Tested on Debian 11, 5.10.0-19-amd64, SMP Debian 5.10.149-2, KDE Plasma Version 5.20.5

I can't replicate the problem on my laptop.
That seems to be quite an old version of KDE Plasma, so it's possible that my widget uses a newer Qt library than you have.

Can you please enable debug logging?

`cd ~/.local/plasma/plasmoids/org.kde.weatherWidget-2/`

apply [the attached diff patch.txt](https://github.com/blackadderkate/weather-widget-2/files/9943759/patch.txt) and then run the widget using

`plasmoidviewer -a . `

and send me the logs...

Thanks in advance.

**Comment by mikewii** [comment]
Qt version on debian 11 is 5.15.2
on debian 11 widget located at 
`~/.local/share/plasma/plasmoids/org.kde.weatherWidget-2/`

with debug enabled, widget settings messed up, and it cant even reach loading weather info

settings messed up even without debug enabled, need to move and reopen settings window to see them

and now it suddenly working! (without debug on)
i have no idea what changed but it was broken yesterday...
here log just to be sure...this is without debugging, and i needed to maximize settings window to see them
[out.log](https://github.com/blackadderkate/weather-widget-2/files/9943860/out.log)

and same log with debug on, it cant reach weather info update it seems
[out_debug.log](https://github.com/blackadderkate/weather-widget-2/files/9943863/out_debug.log)

**Comment by blackadderkate** [comment]
I think your widget may be corrupt. The error messages on the debug log don't make sense.

Try deleting the entire ".local/share/plasma/plasmoids/org.kde.weatherWidget-2/" folder, and reinstalling the [latest version of the widget](https://github.com/blackadderkate/weather-widget-2/releases/download/v2.3.4.3/weather-widget-2.3.4.3.plasmoid) using [the instructions on the wiki](https://github.com/blackadderkate/weather-widget-2/wiki/How-to-install-the-Widget---manual-download).

You'll need to logout & back in again to reload the widget (or kill the plasmashell process and restart it)...

**Comment by mikewii** [comment]
installed debian 11 on vm for testing, and that one cant show widget main window with error:

Error loading QML file: file:///home/test/.local/share/plasma/plasmoids/org.kde.weatherWidget-2/contents/ui/main.qml:120:5: Type OpenWeatherMap unavailable
file:///home/test/.local/share/plasma/plasmoids/org.kde.weatherWidget-2/contents/ui/providers/OpenWeatherMap.qml:18:1: module "QtQuick.XmlListModel" is not installed

**Comment by idamir** [comment]
> QtQuick.XmlListModel

Install qml-module-qtquick-xmllistmodel package.
